/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab7bai1_2_3;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh Hoanfg
 */
public class Lab7Bai1_2_3 extends javax.swing.JFrame {

    List<SinhVien> list = new ArrayList<>();

    /**
     * Creates new form DemoJTable
     */
    public Lab7Bai1_2_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablethongtin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txtdiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btncapnhat = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        cbnganh = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txthocluc = new javax.swing.JTextField();
        ckthuong = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnbyname = new javax.swing.JButton();
        btnbydiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablethongtin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ và tên", "Điểm", "Ngành", "Học lực", "Thưởng"
            }
        ));
        tablethongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablethongtinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablethongtin);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bảng thông tin sinh viên");

        jLabel3.setText("Họ và tên :");

        jLabel5.setText("Điểm :");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btncapnhat.setText("Cập nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        cbnganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lập trình ứng dụng di động", "Thiết kế web", "Hộ thống IOT", "Trí tuệ nhân tạo" }));

        jLabel7.setText("Học lực :");

        txthocluc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoclucActionPerformed(evt);
            }
        });

        ckthuong.setText("Có phần thưởng ?");

        jLabel2.setText("Ngành học :");

        jButton1.setText("Nhập mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnbyname.setText("Sắp xếp theo tên");
        btnbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbynameActionPerformed(evt);
            }
        });

        btnbydiem.setText("Sắp xếp theo điểm");
        btnbydiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbydiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(310, 310, 310)))
                            .addComponent(btnthem)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnbyname)
                                .addGap(18, 18, 18)
                                .addComponent(btnbydiem))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnthoat)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbnganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthocluc, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckthuong))
                        .addGap(168, 168, 168))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btncapnhat)
                        .addGap(56, 56, 56)
                        .addComponent(btnxoa)
                        .addGap(60, 60, 60)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbnganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txthocluc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ckthuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btncapnhat)
                    .addComponent(btnxoa)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbyname)
                    .addComponent(btnbydiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        if (Double.parseDouble(txtdiem.getText()) > 10) {
            txtdiem.setText("");
        }
        if (txtdiem.getText().isEmpty() || txthoten.getText().isEmpty()) {
            if (txthoten.getText().isEmpty()) {
                txthoten.setBackground(Color.red);
            } else {
                txthoten.setBackground(Color.white);
            }
            if (txtdiem.getText().isEmpty()) {
                txtdiem.setBackground(Color.red);
            } else {
                txtdiem.setBackground(Color.white);
            }
            JOptionPane.showMessageDialog(this, "Không được để trống!", "", JOptionPane.ERROR_MESSAGE);
        } else {
            txthoten.setBackground(Color.white);
            txtdiem.setBackground(Color.white);
            addSinhVien();
            fillToTable();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void txthoclucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoclucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoclucActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        int position = tablethongtin.getSelectedRow();
        if (position == -1) {
            JOptionPane.showMessageDialog(this, "Chọn hàng để thực hiện!", "", JOptionPane.ERROR_MESSAGE);
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa ?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (choice == 0) {
                removeSinhVien();
                fillToTable();
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        int position = tablethongtin.getSelectedRow();
        if (position == -1) {
            JOptionPane.showMessageDialog(this, "Chọn hàng để thực hiện!", "", JOptionPane.ERROR_MESSAGE);
        } else {
            updateSinhVien();
            fillToTable();

        }
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void tablethongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablethongtinMouseClicked
        int index = tablethongtin.getSelectedRow();
        SinhVien sv = list.get(index);
        txthoten.setText(sv.getName());
        txtdiem.setText(String.valueOf(sv.getDiem()));
        cbnganh.setSelectedItem(sv.getNganh());
        txthocluc.setText(sv.getGrade());
        ckthuong.setSelected(sv.isBonus());
    }//GEN-LAST:event_tablethongtinMouseClicked

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn thoát ?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(choice == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnthoatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn nhập mới ?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == 0) {
            newInsertSinhVien();
            fillToTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbydiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbydiemActionPerformed
        orderbyDiem();
        fillToTable();
    }//GEN-LAST:event_btnbydiemActionPerformed

    private void btnbynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbynameActionPerformed
        orderbyTen();
        fillToTable();
    }//GEN-LAST:event_btnbynameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab7Bai1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab7Bai1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab7Bai1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab7Bai1_2_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Lab7Bai1_2_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbydiem;
    private javax.swing.JButton btnbyname;
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbnganh;
    private javax.swing.JCheckBox ckthuong;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablethongtin;
    private javax.swing.JTextField txtdiem;
    private javax.swing.JTextField txthocluc;
    private javax.swing.JTextField txthoten;
    // End of variables declaration//GEN-END:variables

    //Các method xử lý các sự kiện thêm, xóa, sửa, nhập mới và thoát chương trình
    private void addSinhVien() {
        SinhVien sv = new SinhVien();
        sv.setName(txthoten.getText());
        sv.setDiem(Double.parseDouble(txtdiem.getText()));
        sv.setNganh((String) cbnganh.getSelectedItem());
        list.add(sv);
        txthocluc.setText(sv.getGrade());
        ckthuong.setSelected(sv.isBonus());
    }

    private void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tablethongtin.getModel();
        model.setRowCount(0);

        for (SinhVien sv : list) {
            Object[] row = new Object[]{sv.getName(), sv.getDiem(), sv.getNganh(), sv.getGrade(), sv.isBonus()};
            model.addRow(row);
        }
    }

    private void removeSinhVien() {
        int index = tablethongtin.getSelectedRow();
        list.remove(index);
        txthoten.setText("");
        txtdiem.setText("");
        txthocluc.setText("");
        cbnganh.setSelectedIndex(0);
        ckthuong.setSelected(false);
    }

    private void updateSinhVien() {
        int index = tablethongtin.getSelectedRow();
        SinhVien sv = list.get(index);

        sv.setName(txthoten.getText());
        sv.setDiem(Double.parseDouble(txtdiem.getText()));
        sv.setNganh((String) cbnganh.getSelectedItem());
        txthocluc.setText(sv.getGrade());
        ckthuong.setSelected(sv.isBonus());
    }

    private void newInsertSinhVien() {
        txthoten.setText("");
        txtdiem.setText("");
        txthocluc.setText("");
        cbnganh.setSelectedIndex(0);
        ckthuong.setSelected(false);
        list.clear();
    }

    //Sắp xếp danh sách trong table theo tên hoặc điểm.
    private void orderbyDiem() {
        Comparator<SinhVien> com = new Comparator<SinhVien>() {
            @Override
            public int compare(SinhVien o1, SinhVien o2) {
                Double d1 = o1.getDiem();
                Double d2 = o2.getDiem();
                return d1.compareTo(d2);
            }
        };
        Collections.sort(list, com);
    }

    private void orderbyTen() {
        Comparator<SinhVien> com = new Comparator<SinhVien>() {
            @Override
            public int compare(SinhVien o1, SinhVien o2) {
                return o1.getName().compareTo(o2.getName());
            }
        };
        Collections.sort(list, com);
    }
}
